

// 发送缓冲区大小
const int SOCKET_SEND_BUFF = 1024*1024*4; // 4M
// 接收缓冲区大小
const int SOCKET_RECV_BUFF = 1024*1024*4; // 4M

// 发送端口号
const int CLIENT_SOCKET_SEND_PORT = 9007;
const int SERVER_SOCKET_RECV_PORT = CLIENT_SOCKET_SEND_PORT;

// 接收端口号
const int CLIENT_SOCKET_RECV_PORT = 9008;
const int SERVER_SOCKET_SEND_PORT = CLIENT_SOCKET_RECV_PORT;